dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3
  -  smartcontractkit/chainlink@1.9.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'
      - '@chainlink=smartcontractkit/chainlink@1.9.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default: ganache-local
  development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
  goerli:
    verify: True